# netlify.toml
[build]
  command = "npm run build"  # Only builds frontend, no migrations
  publish = "dist"           # Your build output folder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Only anon key is needed for frontend
  SUPABASE_URL = "https://xirmvpbkaxiifpuupklk.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpcm12cGJrYXhpaWZwdXVwa2xrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0ODExNDQsImV4cCI6MjA3MTA1NzE0NH0.0QgeiC0xWi1EW4PT420sVChsnCMd6fsMUnBBwyGAS4Y"
  NODE_VERSION = "22"
