// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xirmvpbkaxiifpuupklk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpcm12cGJrYXhpaWZwdXVwa2xrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0ODExNDQsImV4cCI6MjA3MTA1NzE0NH0.0QgeiC0xWi1EW4PT420sVChsnCMd6fsMUnBBwyGAS4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});